# Generated by Django 6.0.4 on 2026-04-25 08:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.SlugField(blank=True, max_length=64, verbose_name='Код')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID 1С')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизирован')),
            ],
            options={
                'verbose_name': 'Класс материала',
                'verbose_name_plural': 'Классы материалов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=32, verbose_name='Сокр.')),
                ('code', models.SlugField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID 1С')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизирован')),
            ],
            options={
                'verbose_name': 'Ед. изм.',
                'verbose_name_plural': 'Ед. изм.',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.SlugField(blank=True, max_length=64, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID 1С')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизирован')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='materials.materialcategory', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Категория материалов',
                'verbose_name_plural': 'Категории материалов',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('fnp_name', models.CharField(blank=True, max_length=500, verbose_name='Наименование ФНП')),
                ('unit_mass', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Масса на ед. изм.')),
                ('base_currency', models.CharField(default='RUB', max_length=3, verbose_name='Код валюты (базовая)')),
                ('base_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена в базовой валюте за ед. изм.')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('rounding_mode', models.CharField(choices=[('none', 'Не округлять'), ('ceil_unit', 'Округлять вверх до целого'), ('ceil_multiple', 'Округлять вверх до кратного числа')], default='none', max_length=32, verbose_name='Способ округления кол-ва')),
                ('rounding_multiple', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Кратность округления (если выбрано кратно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='ID 1С')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialcategory', verbose_name='Папка / категория')),
                ('material_classes', models.ManyToManyField(blank=True, related_name='materials', to='materials.materialclass', verbose_name='Классы материала')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.unitofmeasure', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'name'], name='materials_m_categor_4fcea6_idx')],
            },
        ),
    ]
