# Generated by Django 6.0.4 on 2026-04-25 08:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_uom_kg_to_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit_mass',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Масса на ед. изм.'),
        ),
    ]
