# Generated by Django 6.0.4 on 2026-04-25 09:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_unit_mass_default_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='base_price',
            field=models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена в базовой валюте за ед. изм.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_mass',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Масса на ед. изм.'),
        ),
    ]
