# Generated by Django 6.0.4 on 2026-04-25 09:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def set_all_base_currency_kzt(apps, schema_editor) -> None:
    Material = apps.get_model("materials", "Material")
    Material.objects.update(base_currency="KZT")


def noop_reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_decimal_three_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alt_currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Альтернативная валюта (код)'),
        ),
        migrations.AddField(
            model_name='material',
            name='alt_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена в альтернативной валюте за ед. изм.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='base_currency',
            field=models.CharField(default='KZT', max_length=3, verbose_name='Код валюты (базовая)'),
        ),
        migrations.RunPython(set_all_base_currency_kzt, noop_reverse),
    ]
