# Generated by Django 6.0.4 on 2026-04-25 09:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_alt_to_table(apps, schema_editor) -> None:
    Material = apps.get_model("materials", "Material")
    MatAlt = apps.get_model("materials", "MaterialAlternativePrice")
    for m in Material.objects.all().only("id", "alt_currency", "alt_price"):
        if m.alt_currency and m.alt_price is not None:
            MatAlt.objects.get_or_create(
                material_id=m.id,
                currency=str(m.alt_currency)[:3].upper(),
                defaults={"price": m.alt_price},
            )


def add_editor_perms(apps, schema_editor) -> None:
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    try:
        g = Group.objects.get(name="Редактор материалов")
    except Group.DoesNotExist:
        return
    p = Permission.objects.filter(
        content_type__app_label="materials",
        content_type__model="materialalternativeprice",
    )
    g.permissions.add(*list(p))


def strip_editor_perms(apps, schema_editor) -> None:
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    try:
        g = Group.objects.get(name="Редактор материалов")
    except Group.DoesNotExist:
        return
    p = Permission.objects.filter(
        content_type__app_label="materials",
        content_type__model="materialalternativeprice",
    )
    g.permissions.remove(*list(p))


def noop(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0007_kzt_base_alt_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialAlternativePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True, max_length=3, verbose_name="Код валюты (ISO 4217)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Цена за ед. изм.",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_prices",
                        to="materials.material",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена в альтернативной валюте",
                "verbose_name_plural": "Цены в альтернативных валютах",
                "ordering": ["currency"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "currency"),
                        name="materials_mat_alt_currency_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_alt_to_table, noop),
        migrations.RemoveField(
            model_name="material",
            name="alt_currency",
        ),
        migrations.RemoveField(
            model_name="material",
            name="alt_price",
        ),
        migrations.RunPython(add_editor_perms, strip_editor_perms),
    ]
