# Generated by Django 6.0.4 on 2026-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alt_prices_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='article',
            field=models.CharField(blank=True, db_index=True, help_text='Артикул / внутренний код (для сопоставления с учётом, в т.ч. 1С).', max_length=128, verbose_name='Артикул'),
        ),
    ]
