# Generated by Django 5.x

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def refresh_editor_perms(apps, schema_editor) -> None:
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    g = Group.objects.filter(name="Редактор материалов").first()
    if g:
        perms = Permission.objects.filter(content_type__app_label="materials")
        g.permissions.set(perms)


def noop(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0009_material_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOperationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=500, verbose_name="Операция")),
                ("model_parameter", models.CharField(blank=True, max_length=500, verbose_name="Параметр с модели")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Цена (KZT)",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_lines",
                        to="materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_lines",
                        to="materials.unitofmeasure",
                        verbose_name="Ед. изм.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция (строка)",
                "verbose_name_plural": "Операции",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRelatedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Количество",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_items",
                        to="materials.material",
                        verbose_name="Материал (основной)",
                    ),
                ),
                (
                    "related_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_in_materials",
                        to="materials.material",
                        verbose_name="Сопутствующий материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сопутствующий материал",
                "verbose_name_plural": "Сопутствующие материалы",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialrelateditem",
            constraint=models.UniqueConstraint(
                fields=("parent", "related_material"), name="materials_companion_parent_related_uniq"
            ),
        ),
        migrations.RunPython(refresh_editor_perms, noop),
    ]
