# Generated by Django 6.0.4 on 2026-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_companion_and_operations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('article', ''), _negated=True), fields=('article',), name='materials_material_article_nonempty_uniq'),
        ),
    ]
