# Generated by Django 6.0.4 on 2026-04-25 11:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_material_article_unique_nonempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='calc_type',
            field=models.CharField(default='tape', max_length=32, verbose_name='Тип (калькулятор)'),
        ),
        migrations.AddField(
            model_name='material',
            name='cut_coeff',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Коэф. с учётом раскроя'),
        ),
        migrations.AddField(
            model_name='material',
            name='designation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='material',
            name='max_length',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. длина'),
        ),
        migrations.AddField(
            model_name='material',
            name='max_width',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. ширина'),
        ),
        migrations.AddField(
            model_name='material',
            name='thickness',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Толщина'),
        ),
    ]
