# Generated by Django 6.0.4 on 2026-04-25 12:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_material_calc_type_material_cut_coeff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tex_mirror',
            field=models.BooleanField(default=False, verbose_name='Зеркальность'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_offset_x',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='Смещение X'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_offset_y',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='Смещение Y'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_opacity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Прозрачность'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_rotation_deg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Угол поворота (градусы)'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_specular_brightness',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.35'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Яркость блика'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_specular_sharpness',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Резкость блика'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_step_x',
            field=models.DecimalField(decimal_places=3, default=Decimal('100'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Шаг X'),
        ),
        migrations.AddField(
            model_name='material',
            name='tex_step_y',
            field=models.DecimalField(decimal_places=3, default=Decimal('100'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Шаг Y'),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_color',
            field=models.CharField(blank=True, default='', help_text='Например #RRGGBB', max_length=16, verbose_name='Цвет (HEX)'),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_image',
            field=models.ImageField(blank=True, null=True, upload_to='textures/', verbose_name='Текстура (файл)'),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_mode',
            field=models.CharField(default='texture', help_text='color или texture', max_length=16, verbose_name='Режим текстуры'),
        ),
    ]
