# Generated by Django 6.0.4 on 2026-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_material_tex_mirror_material_tex_offset_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='texture_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='textures/', verbose_name='Текстура (файл)'),
        ),
    ]
