# Generated by Django 6.0.4 on 2026-04-25 13:36

import django.db.models.deletion
from django.db import migrations, models


def refresh_editor_perms(apps, schema_editor) -> None:
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    g = Group.objects.filter(name="Редактор материалов").first()
    if g:
        perms = Permission.objects.filter(content_type__app_label="materials")
        g.permissions.set(perms)


def noop(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0014_alter_material_texture_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculator_profile",
                        to="materials.material",
                        verbose_name="Материал профиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль калькулятора",
                "verbose_name_plural": "Профили калькулятора",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CalculatorProfileColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "color_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculator_color_in_profiles",
                        to="materials.material",
                        verbose_name="Материал (цвет)",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="materials.calculatorprofile",
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет профиля",
                "verbose_name_plural": "Цвета профилей",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="calculatorprofilecolor",
            constraint=models.UniqueConstraint(
                fields=("profile", "color_material"),
                name="materials_calc_profile_color_uniq",
            ),
        ),
        migrations.RunPython(refresh_editor_perms, noop),
    ]

