# Generated by Django 6.0.4 on 2026-04-25 17:10

from django.db import migrations, models
import django.db.models.deletion


def refresh_editor_perms(apps, schema_editor) -> None:
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    g = Group.objects.filter(name="Редактор материалов").first()
    if g:
        perms = Permission.objects.filter(content_type__app_label="materials")
        g.permissions.set(perms)


def noop(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0015_calculator_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatorProfileType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название типа профиля")),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL картинки для отображения в карточке типа профиля.",
                        max_length=1000,
                        verbose_name="Картинка (URL)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип профиля (калькулятор)",
                "verbose_name_plural": "Типы профилей (калькулятор)",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CalculatorProfileTypeColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_new", models.BooleanField(default=False, verbose_name="New")),
                ("is_hit", models.BooleanField(default=False, verbose_name="Hit")),
                ("is_sale", models.BooleanField(default=False, verbose_name="Sale")),
                (
                    "color_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculator_color_in_profile_types",
                        to="materials.material",
                        verbose_name="Материал (цвет)",
                    ),
                ),
                (
                    "profile_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="materials.calculatorprofiletype",
                        verbose_name="Тип профиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет типа профиля",
                "verbose_name_plural": "Цвета типов профилей",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="calculatorprofiletypecolor",
            constraint=models.UniqueConstraint(
                fields=("profile_type", "color_material"),
                name="materials_calc_profile_type_color_uniq",
            ),
        ),
        migrations.RunPython(refresh_editor_perms, noop),
    ]

