# Generated by Django 6.0.4 on 2026-04-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_calculator_filling_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorfillingtypematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_filling_in_types', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='calculatorprofilecolor',
            name='color_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_color_in_profiles', to='materials.material', verbose_name='Материал (цвет)'),
        ),
        migrations.AlterField(
            model_name='calculatorprofiletypecolor',
            name='color_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_color_in_profile_types', to='materials.material', verbose_name='Материал (цвет)'),
        ),
    ]
