# Generated by Django 6.0.4 on 2026-05-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_editor_perms_handle_hole_diameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_confirmed', 'Не подтверждён (менеджер свяжется с клиентом)'), ('confirmed', 'Подтверждён'), ('in_production', 'В процессе сборки'), ('ready', 'Готов к выдаче')], db_index=True, default='not_confirmed', max_length=32, verbose_name='Статус')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Имя в заявке')),
                ('contact_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email в заявке')),
                ('contact_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Снимок калькулятора')),
                ('pdf_file', models.FileField(upload_to='facade_orders/pdf/%Y/%m/', verbose_name='PDF расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facade_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ (фасад, калькулятор)',
                'verbose_name_plural': 'Заказы (фасады, калькулятор)',
                'ordering': ['-created_at'],
            },
        ),
    ]
