# Generated by Django 6.0.4 on 2026-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0030_drop_fnp_unit_mass_alt_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facadeorder',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Не подтверждён (менеджер свяжется с клиентом)'), ('confirmed', 'Подтверждён'), ('in_production', 'В процессе сборки'), ('ready', 'Готов к выдаче'), ('completed', 'Завершён')], db_index=True, default='not_confirmed', max_length=32, verbose_name='Статус'),
        ),
    ]
