# Generated by Django 5.x

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0031_alter_facadeorder_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaterialOperationLine",
        ),
    ]
