# Generated by Django 6.0.4 on 2026-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0039_rename_modus_snapshot_to_import_export_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='import_export_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Полная строка таблицы (XML/XLSX) для повторного экспорта без потери колонок.', verbose_name='Снимок строки импорта/экспорта'),
        ),
    ]
